hmrc/tracking-consent-frontend

app/uk/gov/hmrc/trackingconsentfrontend/assets/package-lock.json, app/uk/gov/hmrc/trackingconsentfrontend/assets/package.json, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/index.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/ui/renderBanner.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/userPreferenceFactory.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/renderBanner.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/userPreference.spec.ts
This stores the preference but doesn't read it back.
I've used a self-contained cookie library as it makes the unit tests manageable.  I tried to use JSDOM's `CookieJar` but the integration point is difficult to track down and reset.
A few decisions which need reviewing:
- I'm not using secure (https only) cookies, these should be used in production but wouldn't be supported in local development.
- I've set the expiry for 10 years, I'm keen on storing the datetime that the user set the preferences so we can use that to invalidate them when we want to.  The approach I've chosen means we can choose to ask again for the user's preference after a year if we want/need to but we're not limited to doing that for technical reasons.  Some of our users will use the site annually.
- I put the event …
=> Store preference for users who Accept All

.gitignore, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/common/fromEntries.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/settingsFormHandler.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/settingsPage.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/userPreferenceFactory.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/common/fromEntries.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/fixtures/settingsForm.html, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/settingsFormHandler.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/types/Preferences.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/types/UserPreferences.ts
Replaced usage of querySelectorAll with querySelector for IE10 compatibility
Removed whitespace in test fixture
Added types and fixed type issues highlighted by type checks e.g. unsafe referencing of checked on nullable
Use ES6 string templates
=> Fixed issues with querySelectorAll on IE10, refactor

app/uk/gov/hmrc/trackingconsentfrontend/config/AppConfig.scala, app/uk/gov/hmrc/trackingconsentfrontend/views/ConsentHead.scala.html, test/uk/gov/hmrc/trackingconsentfrontend/controllers/ConsentPartialControllerSpec.scala
This means that running a service that calls tracking-consent-frontend
can specify the host & port in local development. Will be essential for
service-manager running too, so everything 'just works'
=> BDOG-726: Enabling running with an assets prefix

app/uk/gov/hmrc/trackingconsentfrontend/assets/src/domain/userPreferenceFactory.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/entrypoints/servicePage.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/entrypoints/settingsPage.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/interfaces/preferenceCommunicatorFactory.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/src/ui/renderBanner.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/domain/userPreference.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/interfaces/sendPreferencesFactory.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/ui/renderBanner.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/ui/settingsFormHandler.spec.ts
This includes the interface for the communicator (currently communicating with GTM).
This PR also includes communicating with GTM when:
- The user hits accept all
- The preferences page is saved
- Each page loads when the user has consented
=> BDOG-709 & BODG-722 triggering GTM events

app/uk/gov/hmrc/trackingconsentfrontend/assets/package.json, build.sbt, project/Webpack.scala
This PR runs webpack in watch mode in the background while running sbt run as per https://www.playframework.com/documentation/2.6.16/SBTCookbook
Any changes to files in the Javascript directory trigger a rebuild of the bundles.
=> PLATUI-467: Add webpack watch to sbt run

test/acceptance/pages/CookieSettingsPage.scala, test/acceptance/pages/ServiceTestPage.scala, test/support/TestConfiguration.scala, test/support/TestServer.scala
We need to be able to run the local test server on port 6001 in the build because only ports 6001 to 6010 are mapped back to the Jenkins build agent from the Chrome container.
=> PLATUI-510: Make test server port configurable

run_a11y_tests.sh, run_acceptance_tests_dev.sh, test/acceptance/TestServerSpec.scala, test/resources/application.conf, test/support/TestServer.scala
Run test server only if running locally (i.e. as part of initial build or on local development machine)
Add script to run a11y tests
=> PLATUI-510: Conditionally run test server

build.sbt, conf/application.conf, project/plugins.sbt
Follow best practices for assets as per: https://www.playframework.com/documentation/2.7.x/AssetsOverview
Compress all assets using gzip
Reduce default TTL of assets from 3600 seconds to
- 60 seconds for tracking.js and tracking-transitional.js
- 0 seconds for the cookie settings page assets
In practice most requests will be using the Etag resulting in a 304 Not Modified response. Having a TTL > 0 for tracking.js will reduce the load on the server for this shared asset.
=> PLATUI-573: Add compression and reduce TTL of assets from 3600 seconds

app/uk/gov/hmrc/trackingconsentfrontend/assets/styles/_govuk-frontend.scss, app/uk/gov/hmrc/trackingconsentfrontend/assets/styles/_typography.scss, app/uk/gov/hmrc/trackingconsentfrontend/testonly/controllers/LegacyTestController.scala, app/uk/gov/hmrc/trackingconsentfrontend/testonly/views/LegacyTestPage.scala.html, conf/testOnlyDoNotUseInAppConf.routes, test/acceptance/AcceptanceTestServerSpec.scala, test/acceptance/pages/BasePage.scala, test/acceptance/pages/LegacyServiceTestPage.scala, test/acceptance/specs/BaseAcceptanceSpec.scala, test/acceptance/specs/CookieSettingsPageSpec.scala, test/acceptance/specs/LegacyTestPageSpec.scala, test/acceptance/specs/ServiceTestPageSpec.scala, test/resources/logback-test.xml, test/support/AcceptanceTestServer.scala, test/unit/SpecBase.scala
Suppress unintended generation of @font-face rules linking to non-existent font assets
Use font-family with preference for GDS Transport falling back to nta, falling back to Arial
Add new test page reproducing issue and tests for console errors
=> PLATUI-631: Fixes font-related console errors

app/uk/gov/hmrc/trackingconsentfrontend/testonly/views/LegacyTestPage.scala.html, test/acceptance/specs/CookieSettingsPageSpec.scala
Removing console errors checking for cookie-settings page for now. GTM is attempting to load in an image over http causing CSP violations when running accessibility tests locally only. We need to do more work to determine root cause and provide a sensible workaround.
=> PLATUI-631: Suppress requests for favicon.ico to prevent console errors

conf/application.conf, test/acceptance/specs/CookieSettingsPageSpec.scala
When GTM is running locally over HTTP during Jenkins acceptance or a11y testing, it intermittently includes an image that is also served over HTTP (because our CSP rules only allow requests to www.googletagmanager.com over HTTPS).
This updates the CSP img-src settings to http://www.googletagmanager.com if the page is running over HTTP and to be consistent with the recommended CSP settings at https://developers.google.com/tag-manager/web/csp
It also re-instates the console error check for cookie settings page.
=> PLATUI-637: Fix GTM console errors during local testing

app/uk/gov/hmrc/trackingconsentfrontend/assets/src/common/getReferrer.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/common/getReferrer.spec.ts, app/uk/gov/hmrc/trackingconsentfrontend/assets/test/ui/renderSettingsSaveConfirmationMessage.spec.ts
Passing through the query string, fixing issue with tests that stopped them from working in other orders.
=> PLATUI-916: Passing through the query string.

alert-filters.json
CSRF tokens are not needed for this page because there is no server-side interaction. So silencing this alert.
=> DAST: Filter ZAP ruleID(cweId) 352.

build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
I found that to update sbt-auto-build I had to update the plugin resolvers to the new open artefact store (https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=256476338 which may need a ticket creating to apply change to other repositories we own, because I couldn't see one beside the test leads tickets)
=> PLATUI-1136: Uplift to Play 2.8

build.sbt, docs/maintainers.md, project/plugins.sbt, test/a11y/CookieSettingsSpec.scala, test/unit/SpecBase.scala, test/unit/views/CookieSettingsSpec.scala
I have left the accessibility checks in the `acceptance` tests as i feel they should remain part of acceptance testing.
NOTE: The build is expected to fail because build-jobs is still set to run the sbt task a11yTest which has been removed in the latest sbt-accessibility-linter plugin.
We will need to update the build-jobs after this PR is merged in.
=> Update the sbt-accessibility plugin

docs/maintainers.md
=> PLATUI-1475: remove details of VRT workaround

package-lock.json, package.json
Skipped backstop because the update there doesn't fix the node-fetch issue yet.
=> PLATUI-1623: npm audit fixes

conf/application.conf, test/it/AuditISpec.scala
to allow tracking consent banner on the API Platform's Developer Hub to POST to /audit
=> PLATUI-1673 update CORS configuration

test/acceptance/pages/BasePage.scala, test/acceptance/specs/BaseAcceptanceSpec.scala, test/acceptance/specs/CookieSettingsPageSpec.scala, test/acceptance/specs/LegacyTestPageSpec.scala, test/acceptance/specs/ServiceTestPageSpec.scala
From a bit of searching, it seems that the 502 Bad Gateway error may indicate a cache problem with the browser.  Rather than go down a rabbit hole trying to diagnose and fix that, I've added code to retry any tests that fail and have the `Retryable` tag.
=> PLATUI-2109 retry flickering tests; fix some given/when/then oddities

conf/application.conf
[This PR](https://github.com/hmrc/tracking-consent-frontend/pull/65) added caching explicitly for tracking.js in the `/public/` directory. This was before `optimizely.js` was added to the same directory. At the time, it seems it was set to explicitly set `no-cache` on anything that wasn't `tracking.js`.
Now we want to cache `optimizely.js`, we feel it's more appropriate to set caching on the public directory. This is because our caching rules are also applying to `hmrcfrontend.routes` assets. As such, instead of explicitly setting `optimizely.js`, set the whole directory's cache control headers to `public, max-age=3600` so that users don't need to revalidate after most page visits.
=> PLATUI-2683 sets public directory cache max-age to 1 hour

.gitignore, conf/logback.xml, js/src/domain/userPreferencesFactory.ts, js/test/domain/userPreferencesFactory.spec.ts, package-lock.json, package.json, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
To bump the version of js-cookie, the update is to a new major version of the library, removing a few methods:
- `getJSON()` is now `Cookies.get('foo')`, wrapped in a `JSON.parse()`.
- `set()` now doesn't automatically stringify JSON.
=> PLATUI-3063 update js-cookie and refactor

build.sbt
- Bump scala version to 3.3.4
- wconf now works in scala 3.3.4, utilising msg instead of cat
=> PLATUI-3318 bump scala version
